abraham:
  datasource:
    url: jdbc:mysql://localhost:3306/mas
    username: mas
    password: mas123
    driver-class-name: com.mysql.jdbc.Driver
  jpa-hibernate:
    generate-ddl: true
    show-sql: true
    packages-to-scan: 
      - abraham.core.web.security.domain
      - abraham.core.ca.domain
