abraham:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/mas
    username: mas
    password: mas123
    driverClassName: com.mysql.jdbc.Driver
  jpa-hibernate:
    generate-ddl: true
    show-sql: true
    dialect: org.hibernate.dialect.MySQL5Dialect
    packages-to-scan: 
      - abraham.core.web.security.domain
      - abraham.core.ca.domain
